version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: mgl-postgres
    environment:
      POSTGRES_USER: mgl_user
      POSTGRES_PASSWORD: mgl_pass
      POSTGRES_DB: mgl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
